// Convert terminal mouse click coords to cell (board position)
export default (x, y) => {
    let i;

    if (y === 0) {
        i = 6;
        if (x === i || x === i + 1) return 'C5';
        i += 4;
        if (x === i || x === i + 1) return 'D5';
        i += 4;
        if (x === i || x === i + 1) return 'E5';
        i += 4;
        if (x === i || x === i + 1) return 'F5';
        i += 4;
        if (x === i || x === i + 1) return 'G5';
        i += 4;
        if (x === i || x === i + 1) return 'H5';
        i += 4;
        if (x === i || x === i + 1) return 'I5';
        i += 4;
        if (x === i || x === i + 1) return 'J5';
        i += 4;
        if (x === i || x === i + 1) return 'K5';
    } else if (y === 1) {
        i = 4;
        if (x === i || x === i + 1) return 'B4';
        i += 4;
        if (x === i || x === i + 1) return 'C4';
        i += 4;
        if (x === i || x === i + 1) return 'D4';
        i += 4;
        if (x === i || x === i + 1) return 'E4';
        i += 4;
        if (x === i || x === i + 1) return 'F4';
        i += 4;
        if (x === i || x === i + 1) return 'G4';
        i += 4;
        if (x === i || x === i + 1) return 'H4';
        i += 4;
        if (x === i || x === i + 1) return 'I4';
        i += 4;
        if (x === i || x === i + 1) return 'J4';
        i += 4;
        if (x === i || x === i + 1) return 'K4';
    } else if (y === 2) {
        i = 2;
        if (x === i || x === i + 1) return 'A3';
        i += 4;
        if (x === i || x === i + 1) return 'B3';
        i += 4;
        if (x === i || x === i + 1) return 'C3';
        i += 4;
        if (x === i || x === i + 1) return 'D3';
        i += 4;
        if (x === i || x === i + 1) return 'E3';
        i += 4;
        if (x === i || x === i + 1) return 'F3';
        i += 4;
        if (x === i || x === i + 1) return 'G3';
        i += 4;
        if (x === i || x === i + 1) return 'H3';
        i += 4;
        if (x === i || x === i + 1) return 'I3';
        i += 4;
        if (x === i || x === i + 1) return 'J3';
        i += 4;
        if (x === i || x === i + 1) return 'K3';
    } else if (y === 3) {
        i = 4;
        if (x === i || x === i + 1) return 'A2';
        i += 4;
        if (x === i || x === i + 1) return 'B2';
        i += 4;
        if (x === i || x === i + 1) return 'C2';
        i += 4;
        if (x === i || x === i + 1) return 'D2';
        i += 4;
        if (x === i || x === i + 1) return 'E2';
        i += 4;
        if (x === i || x === i + 1) return 'F2';
        i += 4;
        if (x === i || x === i + 1) return 'G2';
        i += 4;
        if (x === i || x === i + 1) return 'H2';
        i += 4;
        if (x === i || x === i + 1) return 'I2';
        i += 4;
        if (x === i || x === i + 1) return 'J2';
    } else if (y === 4) {
        i = 6;
        if (x === i || x === i + 1) return 'A1';
        i += 4;
        if (x === i || x === i + 1) return 'B1';
        i += 4;
        if (x === i || x === i + 1) return 'C1';
        i += 4;
        if (x === i || x === i + 1) return 'D1';
        i += 4;
        if (x === i || x === i + 1) return 'E1';
        i += 4;
        if (x === i || x === i + 1) return 'F1';
        i += 4;
        if (x === i || x === i + 1) return 'G1';
        i += 4;
        if (x === i || x === i + 1) return 'H1';
        i += 4;
        if (x === i || x === i + 1) return 'I1';        
    }
};